In [ ]:
import numpy as np #allias
# import numpy
# a = numpy.array()(numpy.function)

a = np.array((1,3,9,0,2))`
print(a)

[1 3 9 0 2]


In [ ]:
import numpy as np
b = np.array([1,3,5,7,9])
print(b)

['1' '3' '5' '7' '9']


In [ ]:
np_arr = np.array([3,3,3,3,3.3,'hello',False])
print((np_arr[-1]))

a = False
print(bool(a))

False
False


In [ ]:
np_arr = np.array([3,3,3,3,3.3,'hello',False])
print(bool(np_arr[-1]))

a = False
print(bool(a))

True
False


In [ ]:
a = 0
print(bool(a))

False


In [ ]:
a = '0'
print(bool(a))

True


In [ ]:
a=np.zeros(5) #1d array
print(a)


[0. 0. 0. 0. 0.]


In [ ]:
a = np.zeros((3,4))
print(a)
print(a.dtype)
print(type(a[0][0]))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
float64
<class 'numpy.float64'>


In [ ]:
a =np.empty((2,3,4) , dtype = int)
print(a)

[[[-4625196817309499392 -4620693217682128896                    0
   -4625196817309499392]
  [ 4598175219545276416 -4620693217682128896  4602678819172646912
   -4625196817309499392]
  [ 4598175219545276416                    0  4602678819172646912
    4598175219545276416]]

 [[ 4598175219545276416  4602678819172646912                    0
    4598175219545276416]
  [-4625196817309499392  4602678819172646912 -4620693217682128896
    4598175219545276416]
  [-4625196817309499392                    0 -4620693217682128896
   -4625196817309499392]]]


In [ ]:
a =np.empty(4 , dtype = int)
print(a)

[876632419         0         1        -1]


In [ ]:
a =np.full((2,3,4) , fill_value=0, dtype = int)
print(a)

[[[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]]


In [ ]:
a =np.full(4,5 ,dtype=int)
print(a)

[5 5 5 5]


In [ ]:
a = np.arange(2 * 3 * 4, dtype = int).reshape((2,3,4))
print(a)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [ ]:
a = np.arange(9, dtype = int).reshape((3,3))
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
a = np.arange(3,12,3)
print(a)

[3 6 9]


In [ ]:
a = np.linspace(0, 23, num=24, dtype=int).reshape((2,3,4))
print(a)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [ ]:
a = np.linspace(3,12,1, dtype=int)
print(a)

[3]


In [ ]:
a = np.linspace(3,12,1, dtype=int)
print(a)

In [ ]:
a = np.shape(a)
print(a)

(1,)


In [ ]:
a = np.size(a)
print(a)

1


In [ ]:
import numpy as np
a = np.random.randint(2, 15,6)
print(a)
b=a.reshape((3,2))
print(b)


[ 4  2  4 14  3  7]
[[ 4  2]
 [ 4 14]
 [ 3  7]]


In [ ]:
a = np.random.choice([0, 1], size=10)
print(a)

[1 1 0 0 0 1 0 0 1 0]


In [ ]:
#corresponding elements
a = np.array([1,2,3,4])
b = np.array([1,3,5,7])
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[ 2  5  8 11]
[ 0 -1 -2 -3]
[ 1  6 15 28]
[1.         0.66666667 0.6        0.57142857]


In [ ]:
concatenate_matrix=np.random.randint(1,10,size=(3,4))
print(concatenate_matrix)

[[7 1 8 1]
 [2 5 8 8]
 [4 5 6 4]]


In [ ]:
a=np.random.randint(2,15,6)
b=np.random.randint(1,19,6)
print(a)
print(b)
c=np.where(b>2,b,a)
print(c)

[9 8 2 2 8 2]
[12 13 13  2  4  5]
[12 13 13  2  4  5]


In [ ]:
scores=input().split()
print(scores)
scores=[int(x)for x in scores]
print(scores)

2345
['2345']
[2345]


HW ques


In [8]:
import numpy as np
# Prices of products in the store
prices=np.array([23,78,90,12,45])
total=np.sum(prices)
minimum=np.min(prices)
maximum=np.max(prices)
std_dev=np.std(prices)
size=np.size(prices)
sort=np.sort(prices)
print(total)
print(minimum)
print(maximum)
print(std_dev)
print(size)
print(sort)

248
12
90
30.269456552769494
5
[12 23 45 78 90]
